'use client';

import { useState, Suspense } from 'react';
import { useSearchParams } from 'next/navigation';
import { Button } from '@/components/common/Button';
import {
  FileText,
  Printer,
  Download,
  Calendar,
  CheckCircle,
  List
} from 'lucide-react';
import { cn } from '@/lib/utils';

interface ExportOptions {
  format: 'pdf' | 'print' | 'markdown';
  includeTranslation: boolean;
  includeAyahNumbers: boolean;
  fontSize: 'small' | 'medium' | 'large';
  surahIds: number[];
  revisionType: string;
}

function ExportContent() {
  const searchParams = useSearchParams();
  const defaultSurahs = searchParams?.get('surahs')?.split(',').map(Number) || [];

  const [options, setOptions] = useState<ExportOptions>({
    format: 'pdf',
    includeTranslation: true,
    includeAyahNumbers: true,
    fontSize: 'medium',
    surahIds: defaultSurahs,
    revisionType: 'sabaq',
  });

  const handleExport = async (format: 'pdf' | 'print' | 'markdown') => {
    setOptions((prev) => ({ ...prev, format }));

    if (format === 'print') {
      window.print();
      return;
    }

    if (format === 'markdown') {
      const content = generateMarkdown(options);
      downloadFile(content, 'revision-sheet.md', 'text/markdown');
      return;
    }

    if (format === 'pdf') {
      // Generate PDF content
      window.print();
    }
  };

  const generateMarkdown = (opts: ExportOptions): string => {
    const date = new Date().toLocaleDateString('en-US', {
      weekday: 'long',
      year: 'numeric',
      month: 'long',
      day: 'numeric'
    });

    return `# Daily Revision Sheet

**Date:** ${date}
**Type:** ${opts.revisionType}

---

## Surahs for Revision

${opts.surahIds.map((id) => `### Surah ${id}`).join('\n\n')}

---

*Generated by Hifz Companion*
`;
  };

  const downloadFile = (content: string, filename: string, mimeType: string) => {
    const blob = new Blob([content], { type: mimeType });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = filename;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="container mx-auto px-4 py-8 max-w-2xl print:max-w-none print:p-0">
      <h1 className="text-2xl font-bold text-gray-900 dark:text-white mb-6 print:hidden">
        Export Revision Sheet
      </h1>

      {/* Export Options */}
      <div className="bg-white dark:bg-gray-800 rounded-xl p-6 mb-6 print:hidden">
        <h2 className="text-lg font-semibold text-gray-900 dark:text-white mb-4">Export Options</h2>

        <div className="space-y-4">
          <div>
            <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
              <List className="w-4 h-4 inline mr-2" />
              Revision Type
            </label>
            <select
              value={options.revisionType}
              onChange={(e) => setOptions((prev) => ({ ...prev, revisionType: e.target.value }))}
              className="w-full px-3 py-2 bg-white dark:bg-gray-700 border border-gray-300 dark:border-gray-600 rounded-lg"
            >
              <option value="sabaq">Sabaq (New)</option>
              <option value="sabaq_para">Sabaq Para (Recent)</option>
              <option value="manzil">Manzil (Old)</option>
            </select>
          </div>

          <div className="flex items-center gap-4">
            <label className="flex items-center gap-2">
              <input
                type="checkbox"
                checked={options.includeTranslation}
                onChange={(e) => setOptions((prev) => ({ ...prev, includeTranslation: e.target.checked }))}
                className="w-4 h-4 text-primary-600 rounded"
              />
              <span className="text-sm text-gray-700 dark:text-gray-300">Include Translation</span>
            </label>
            <label className="flex items-center gap-2">
              <input
                type="checkbox"
                checked={options.includeAyahNumbers}
                onChange={(e) => setOptions((prev) => ({ ...prev, includeAyahNumbers: e.target.checked }))}
                className="w-4 h-4 text-primary-600 rounded"
              />
              <span className="text-sm text-gray-700 dark:text-gray-300">Show Ayah Numbers</span>
            </label>
          </div>

          <div>
            <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
              Font Size
            </label>
            <div className="flex gap-2">
              {(['small', 'medium', 'large'] as const).map((size) => (
                <button
                  key={size}
                  onClick={() => setOptions((prev) => ({ ...prev, fontSize: size }))}
                  className={cn(
                    'px-4 py-2 rounded-lg capitalize',
                    options.fontSize === size
                      ? 'bg-primary-600 text-white'
                      : 'bg-gray-100 dark:bg-gray-700 text-gray-700 dark:text-gray-300'
                  )}
                >
                  {size}
                </button>
              ))}
            </div>
          </div>
        </div>
      </div>

      {/* Export Buttons */}
      <div className="grid grid-cols-3 gap-4 mb-6 print:hidden">
        <Button
          variant="outline"
          className="flex flex-col items-center py-6"
          onClick={() => handleExport('pdf')}
        >
          <FileText className="w-8 h-8 mb-2" />
          <span>PDF</span>
        </Button>
        <Button
          variant="outline"
          className="flex flex-col items-center py-6"
          onClick={() => handleExport('print')}
        >
          <Printer className="w-8 h-8 mb-2" />
          <span>Print</span>
        </Button>
        <Button
          variant="outline"
          className="flex flex-col items-center py-6"
          onClick={() => handleExport('markdown')}
        >
          <Download className="w-8 h-8 mb-2" />
          <span>Markdown</span>
        </Button>
      </div>

      {/* Preview */}
      <div className="bg-white dark:bg-gray-800 rounded-xl p-6 print:shadow-none">
        <div className="flex items-center justify-between mb-4 print:hidden">
          <h2 className="text-lg font-semibold text-gray-900 dark:text-white">Preview</h2>
          <span className="text-sm text-gray-500">Print this page for physical revision</span>
        </div>

        <div
          className={cn(
            'print-content',
            options.fontSize === 'small' && 'text-sm',
            options.fontSize === 'medium' && 'text-base',
            options.fontSize === 'large' && 'text-lg'
          )}
        >
          <div className="text-center mb-8 print:mb-4">
            <h1 className="text-xl font-bold mb-2">Daily Revision Sheet</h1>
            <p className="text-gray-600 dark:text-gray-400">
              <Calendar className="w-4 h-4 inline mr-1" />
              {new Date().toLocaleDateString('en-US', {
                weekday: 'long',
                year: 'numeric',
                month: 'long',
                day: 'numeric'
              })}
            </p>
            <p className="text-sm text-gray-500 capitalize mt-1">
              Type: {options.revisionType.replace('_', ' ')}
            </p>
          </div>

          <div className="border-t border-gray-200 dark:border-gray-700 pt-6">
            <div className="mb-4">
              <div className="flex items-center gap-2 mb-2">
                <CheckCircle className="w-4 h-4 text-gray-400" />
                <h3 className="font-medium">Surahs for Revision</h3>
              </div>
              <div className="space-y-2 pl-6">
                {options.surahIds.length > 0 ? (
                  options.surahIds.map((id) => (
                    <div key={id} className="flex items-center gap-2">
                      <div className="w-4 h-4 border-2 border-gray-300 dark:border-gray-600 rounded" />
                      <span>Surah {id}</span>
                    </div>
                  ))
                ) : (
                  <p className="text-gray-500 text-sm">No surahs selected</p>
                )}
              </div>
            </div>

            <div className="mt-8 text-center text-sm text-gray-500">
              <p>☐ Completed ☐ Needs Review</p>
            </div>
          </div>

          <div className="mt-8 pt-4 border-t border-gray-200 dark:border-gray-700 text-center text-xs text-gray-400 print:mt-4">
            Generated by Hifz Companion • {new Date().toISOString().split('T')[0]}
          </div>
        </div>
      </div>

      <style jsx global>{`
        @media print {
          body * {
            visibility: hidden;
          }
          .print-content,
          .print-content * {
            visibility: visible;
          }
          .print-content {
            position: absolute;
            left: 0;
            top: 0;
            width: 100%;
          }
        }
      `}</style>
    </div>
  );
}

export default function ExportPage() {
  return (
    <Suspense fallback={<div className="container mx-auto px-4 py-8">Loading...</div>}>
      <ExportContent />
    </Suspense>
  );
}
